# Add your additional Hyprland configurations here
# 
# This is an additional key binding 
# bind = $mainMod CTRL, up, workspace, empty
# 
# Example for xwayland
# xwayland {
#   force_zero_scaling = true
# }

# qt5ct environment variable
# env = QT_QPA_PLATFORMTHEME,qt5ct

# SDL version
env = SDL_VIDEODRIVER,wayland
# env = SDL_VIDEODRIVER,x11

# No Hardware Cursor
# cursor {
#     no_hardware_cursors = false
# }

# Load nwg-dock-hyprland
# Install it first with the installation options
exec-once = ~/.config/nwg-dock-hyprland/launch.sh

plugin {
  hyprbars {
    bar_height = 35

    hyprbars-button = rgb(ed2939), 16, , hyprctl dispatch killactive
    hyprbars-button = rgb(4169e1), 16, , hyprctl dispatch fullscreen 1
    hyprbars-button = rgb(a9a9a9), 16, , hyprctl dispatch movetoworkspacesilent special:MinimizedApps
  }
}

# Autostart
exec-once = hyprpm reload -nn
