# .tmux.conf - tmux configuration source-file

# change prefix to C-s
set -g prefix C-s

set -g status-position top

# enable mouse
set -g mouse on 

# reload config
unbind r
bind r source-file ~/.tmux.conf

# split panes using | and -
unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

# switch panes using hjkl
bind-key h select-pane -L
bind-key j select-pane -D 
bind-key k select-pane -U 
bind-key l select-pane -R

# plugins
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "christoomey/vim-tmux-navigator"

set -g @plugin "egel/tmux-gruvbox"
set -g @tmux-gruvbox "dark256" # or 'dark256', 'light', 'light256'
set -g @tmux-gruvbox-statusbar-alpha "true"
set -g @tmux-gruvbox-right-status-x "%d-%m-%Y"
set -g @tmux-gruvbox-right-status-z "#h #{tmux_mode_indicator}"

# initialize TMUX plugin manager 
# (keep this line at the very bottom)
run "~/.tmux/plugins/tpm/tpm"

